data:
  input: "data/data.csv"
  split: "data/split"
mlflow:
  uri : http://ec2-16-112-70-97.ap-south-2.compute.amazonaws.com:5000/
cleaning:
  sentiment_mapping:
    "5 stars": 2
    "4 stars": 2
    "3 stars": 1
    "2 stars": 0
    "1 star": 0
model:
  name: "xlm-roberta-base"
  num_labels: 3
  max_length: 64
training:
  epochs: 3
  batch_size: 16
  lr: 1e-5
  weight_decay: 0.01
augmentation:
  target_langs: ['en', 'fr', 'es', 'de', 'it']